description: What's in Kev's Head? Well here it is

hb:
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  logo: false
  header:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: bigmadkev
      twitter: bigmadkev
      linkedin: kevmccabe
      instagram: bigmadkev
      threads: bigmadkev
  footer:
    powered_by: false
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      _color: true # when false, remove the color of social icons.
      github: bigmadkev
      twitter: bigmadkev
      linkedin: kevmccabe
      instagram: bigmadkev
      threads: bigmadkev
  blog:
    full_width: true # when true, the blog layout takes full width.
    sidebar:
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
    paginate: 12 # paginate.
    post_thumbnail: true # whether to show the thumbnails.
    post_date_format: ":date_full" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 5 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - blog
        - tutorials
    giscus:
      repo: hbstack/theme
      repo_id: R_kgDOJP3qtA
      category_id: DIC_kwDOJP3qtM4CVavM
  docs:
    giscus:
      repo: hbstack/theme
      repo_id: R_kgDOJP3qtA
      category_id: DIC_kwDOJP3qtM4CVavM

  # gallery:
  #   thumbnail_size: "x640"

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.

# see https://hugomods.com/en/docs/search/#site-parameters
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
