# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: New Content

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      archetype:
        type: choice
        description: 'Define arche type'
        options:
          - 'blog'
          - 'docs'
          - 'tutorials'
          - 'gallery'
        required: true
        default: 'blog'
      title:
        type: string
        description: 'Define content title'
        required: true
        default: ''

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.25.3
      HUGO_VERSION: 0.152.2
      TZ: Europe/London
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Install Hugo
        run: |
          curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          mkdir "${HOME}/.local/hugo"
          tar -C "${HOME}/.local/hugo" -xf "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          rm "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          echo "${HOME}/.local/hugo" >> "${GITHUB_PATH}"
      - name: Verify installations
        run: |
          echo "Go: $(go version)"
          echo "Hugo: $(hugo version)"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Create new content with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          CONTENT_FOLDER: content
        run: |
          TITLE="${{ github.event.inputs.title }}"
          TITLE=${TITLE//[^[:alnum:]]/-} # replace all non alpha numerics with hyphens
          hugo \
            new content ${{ github.event.inputs.archetype }}/${TITLE}/index.md \
            --force \
            -k ${{ github.event.inputs.archetype }} \
            -c ${{ github.workspace }}/${CONTENT_FOLDER} \
            -e ${HUGO_ENV}
      - name: Commit New Content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.email "no-reply@github.com"
            git config --global user.name "GitHub Actions"
            git add ${{ github.workspace }}/${CONTENT_FOLDER}/\*
            git commit -m "Creating New Content"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push
